apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: new-taskrun
spec:
  serviceAccountName: tutorial-service
  taskRef:
    name: new-task
  params:
    - name: pathToDockerFile
      value: images/ibm-cloud/Dockerfile
      # - name: pathToContext
      #value: /workspace/docker-source #$(resources.inputs.docker-source.path)/examples/microservices/leeroy-web #configure: may change according to your source
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: ibmcloud-git
    outputs:
      - name: builtImage
        resourceRef:
          name: ibmcloud-image
